name: 01-building-blocks

on: workflow_dispatch

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Goodbye
        run: echo "Goodbye, World!"
  echo-hello-again:
    runs-on: ubuntu-latest
    steps:
      - name: failed step 
        run: |
          echo "Hello, World! failed!"
          exit 0
  echo-goodbye-again:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Goodbye
        run: echo "Goodbye, World!"


